### ISSUE TITLE
Build failure in LLVMAttribute

### ISSUE THREAD

**Issue by kvark** [servo/osmesa-src#16] opened 2017-07-17 21:22 UTC
Steps:
```
git clone https://github.com/servo/osmesa-src
cd osmesa-src
cargo test
```
Result (starting from the first error):
```
In file included from /home/kvark/Code/osmesa-src/mesa-12.0.1/src/gallium/auxiliary/draw/draw_llvm.c:45:0:
/home/kvark/Code/osmesa-src/mesa-12.0.1/src/gallium/auxiliary/gallivm/lp_bld_intr.h:69:20: error: unknown type name ‘LLVMAttribute’; did you mean ‘LLVMAttributeRef’?
                    LLVMAttribute attr);
                    ^~~~~~~~~~~~~
                    LLVMAttributeRef
/home/kvark/Code/osmesa-src/mesa-12.0.1/src/gallium/auxiliary/draw/draw_llvm.c: In function ‘draw_llvm_generate’:
/home/kvark/Code/osmesa-src/mesa-12.0.1/src/gallium/auxiliary/draw/draw_llvm.c:1615:10: error: implicit declaration of function ‘LLVMAddAttribute’; did you mean ‘LLVMIsEnumAttribute’? [-Werror=implicit-function-declaration]
          LLVMAddAttribute(LLVMGetParam(variant_func, i),
          ^~~~~~~~~~~~~~~~
          LLVMIsEnumAttribute
/home/kvark/Code/osmesa-src/mesa-12.0.1/src/gallium/auxiliary/draw/draw_llvm.c:1616:27: error: ‘LLVMNoAliasAttribute’ undeclared (first use in this function); did you mean ‘LLVMIsStringAttribute’?
                           LLVMNoAliasAttribute);
                           ^~~~~~~~~~~~~~~~~~~~
                           LLVMIsStringAttribute
/home/kvark/Code/osmesa-src/mesa-12.0.1/src/gallium/auxiliary/draw/draw_llvm.c:1616:27: note: each undeclared identifier is reported only once for each function it appears in
/home/kvark/Code/osmesa-src/mesa-12.0.1/src/gallium/auxiliary/draw/draw_llvm.c: In function ‘draw_gs_llvm_generate’:
/home/kvark/Code/osmesa-src/mesa-12.0.1/src/gallium/auxiliary/draw/draw_llvm.c:2162:27: error: ‘LLVMNoAliasAttribute’ undeclared (first use in this function); did you mean ‘LLVMIsStringAttribute’?
                           LLVMNoAliasAttribute);
                           ^~~~~~~~~~~~~~~~~~~~
                           LLVMIsStringAttribute
cc1: some warnings being treated as errors
make[4]: *** [Makefile:2145: draw/draw_llvm.lo] Error 1
make[4]: *** Waiting for unfinished jobs....
make[3]: *** [Makefile:600: all-recursive] Error 1
make[2]: *** [Makefile:701: all-recursive] Error 1
make[1]: *** [Makefile:579: all] Error 2
make: *** [Makefile:645: all-recursive] Error 1
thread 'main' panicked at 'failed with: exit code: 2', build.rs:52
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```
Full log: https://pastebin.mozilla.org/9027382

**Comment by emilio** [comment] 2017-07-17 21:24
Dupe of #14

**Comment by emilio** [comment] 2017-07-17 21:24
I really should get that builder failure figured out though...

**Closed as completed by emilio** 2017-07-17 21:24 UTC
Labels: bug

**Comment by kvark** [comment] 2017-07-17 21:27
Ah, sorry @emilio . I looked at the date of the issue (Nov 2016) and didn't believe it can be that old.
